### ISSUE TITLE
Prepare for Polkadex Parachain

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#232]
Decide how to maintain polkadex parachain code, local testing, and deployment framework.

- [ ] Setup Local Relaychain for Testing Parachain logic
- [ ] Initialize parachain template in this repo
- [ ] Setup CI/CD for parachain testing

Reference:
Cumulus:  https://github.com/paritytech/cumulus
Parachain Template: https://github.com/substrate-developer-hub/substrate-parachain-template
Substrate to Substrate Bridge: https://github.com/paritytech/parity-bridges-common

Here are components which we will need https://github.com/open-web3-stack/open-runtime-module-library
